Use a prebuilt image of Saleor core
saleor/saleor-platform pull request #238
Opened 2023-02-12 21:09 UTC by patrys

It doesn't make sense for users to rebuild Saleor. We already provide Docker images.

2023-02-17 17:32 UTC, lkostrowski requested changes

2023-02-17 17:32 UTC, lkostrowski commented on .github/workflows/test-platfomr.yml
> +name: test-platform
typo in the filename

2023-02-20 16:55 UTC, andrzejewsky approved these changes

2023-02-21 07:09 UTC, lkostrowski approved these changes

2023-02-21 14:29 UTC, krzysztofwolski approved these changes

2023-02-22 10:57 UTC, peelar approved these changes

2023-02-22 10:58 UTC, merged

2023-02-23 13:14 UTC, mhcassiem commented
hi, what was the motivation behind removing storefront from platform?
How would you recommend allowing storefront to hit saleor-core?

2023-02-23 13:21 UTC, andrzejewsky commented
Hey @mhcassiem - the motivation here is to deliver an environment that you can use to build something on top of Saleor, for example, a storefront, checkout, an external app, and so on. By using the platform you should be able to easily bootstrap Saleor (core API + its dashboard) without digging into details. 

Storefront or the other external projects that are talking to Saleor, you can quickly bootstrap by using their own development mode (simply using a package manager) and configuring where the API is (in the case of saleor platform, dockerized version is on localhost:8000).

2023-02-23 13:21 UTC, patrys commented
As I mentioned in the top comment, we want to ensure each project offers an optimized development experience. Platform was a poor fit for that. It ended up being neither suitable for development nor production use. Most people don't need to edit the core or the dashboard, so we want them to be deployable quickly (and using official images) and in tandem with other repositories offering dev container setup optimized for working on storefronts/checkout/payments/etc.

Including everything in the platform does not scale, we have dozens of apps and other satellite services using Saleor, and you don't want them all running on your laptop so that you can edit the storefront.

2023-02-23 14:55 UTC, mhcassiem commented
Thank you. I've noticed build times are much faster now. However I encountered an error with react-storefront. 
I was getting ECONNREFUSED for the graphql endpoint.

This was due to the nginx proxying. However, I was running storefront from its own compose file and because of nginx could not proxy to api:8000. I've found a fix in the meantime by connecting the storefront services to the same docker network as saleor-core.

I assume I should probably open an issue in react-storefront for this?

2023-02-23 16:33 UTC, patrys commented
@mhcassiem Yes, please open a ticket in the storefront repository. We'll get it fixed.