Add script to prepare platform setup to run automation tests.
saleor/saleor-platform pull request #317
Opened 2024-10-15 12:38 UTC by kadewu

The script takes the snapshot named: `update-automation-snapshot.sql`
and makes sure that it is running on `public` schema instead of defined one in the script.

Next it makes sure to correctly import the snapshot and fill missing migrations if new ones appeared after snapshot was taken.

2024-10-15 12:41 UTC, michalina-graczyk commented
Instruction how to use it: https://www.notion.so/saleor/Instructions-to-Set-Up-the-Platform-for-e2e-Tests-9c0460e78aff4d9f96bb84094408089d?pvs=4

2024-10-15 12:42 UTC, michalina-graczyk approved these changes

2024-10-15 13:12 UTC, andrzejewsky requested changes
Two things:
1. please add a few line of comment in this script what is exactly for, mention that it is for loading database, that you need saleor platform repo with link to it etc.
2. name is it really "run-automation", this file does the database loading & migration, perhaps "setup-e2e-db.sh" would be more accrutate?

2024-10-29 11:34 UTC, andrzejewsky approved these changes

2024-10-29 11:34 UTC, merged